version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/opt/app
    command: ["mix", "test"]
